# -----------------------------------------------------------------------------
# GENERAL
# -----------------------------------------------------------------------------
backend = "glx";
vsync = true;
detect-trasient = true;
detect-client-leader = true;
xrender-sync-fence = true;
refresh-rate = 75;

# -----------------------------------------------------------------------------
# SHADOWS
# -----------------------------------------------------------------------------
shadow = false;
frame = false;

# -----------------------------------------------------------------------------
# FADING (FADE WINDOWS WHEN OPENING OR CLOSING WINDOWS)
# -----------------------------------------------------------------------------
fading = true;
fade-in-step = 0.0066;
fade-out-step = 0.01;
fade-delta = 1;

# -----------------------------------------------------------------------------
# TRANSPARENCY/OPACITY
# -----------------------------------------------------------------------------
active-opacity = 1;
inactive-opacity = 1;
frame-opacity = 0.5;
inactive-opacity-override = false;

# -----------------------------------------------------------------------------
# BACKGROUND BLURRING
# -----------------------------------------------------------------------------
blur-method = "dual_kawase";
blur-strength = 5;
# -----------------------------------------------------------------------------
# CORNERS
# -----------------------------------------------------------------------------
corner-radius = 10;
