[General]
activeIndicatorColor=#cfcfcf
activeIndicatorColor2D=#cfcfcf
backgroundColor=#cc000000
backgroundColor2D=#cc000000
borderColor=#000000
bouncingLauncherIcon=true
firstRunWindowCountIndicator=false
floatingMargin=6
inactiveIndicatorColor=#006c6c
inactiveIndicatorColor2D=#006c6c
maximumIconSize=42
minimumIconSize=24
panelStyle=2
showTooltip=false
spacingFactor=0.9
tooltipFontSize=24
zoomingAnimationSpeed=16

[Application%20Menu]
backgroundAlpha=0.8
fontSize=14
label=Applications

[Clock]
fontScaleFactor=1
use24HourClock=true

[TaskManager]
currentDesktopTasksOnly=false
groupTasksByApplication=true
