align=center
separator=false
color=#abb2bf
separator_block_width=4
markup=pango

border_top=2
border_left=2
border_right=2
border_bottom=2
border=#2C2D30

[window_title]
command=echo " <b>$(~/.config/i3/scripts/window-title | tr '[:lower:]' '[:upper:]')</b> "
interval=once
signal=1
markup=pango
border_top=0
border_left=0
border_right=0
border_bottom=0

[time]
command=echo " <b>$(date '+%Hh%M')</b> "
interval=60
color=#24283b
background=#abb2bf
# color=#c0caf5
border_top=0
border_left=0
border_right=0
border_bottom=0

[mediaplayer]
command=echo " $( ~/.config/i3/scripts/mediaplayer ) "
interval=once
signal=10
background=#3e4045
# color=#c0caf5

[volume-mic]
command=echo " $(~/.config/i3/scripts/volume-mic) "
instance=Master
interval=once
signal=11
background=#3e4045
# color=#c0caf5

[arch_update]
command=echo "   $(checkupdates | wc -l) "
interval=once
background=#3e4045
# color=#c0caf5

[disk]
instance=/
command=echo "   $(df -h / | awk 'FNR==2 { gsub(/[A-Za-z]/, ""); printf "%i\n", $4 }') GiB "
interval=60
background=#3e4045
# color=#c0caf5

[gpu_stats]
command=~/.config/i3/scripts/gpu_usage
interval=2
# color=#c0caf5

background=#3e4045

[cpu_stats]
command=~/.config/i3/scripts/cpu_usage
interval=2
# color=#c0caf5
background=#3e4045

[memory]
command=echo "   $(free --giga | awk 'FNR==2{ printf "%i\n", $7 }') GiB "
interval=2
# color=#c0caf5
background=#3e4045

[battery]
command=echo " $(~/.config/i3/scripts/battery2)  "
interval=60
# color=#c0caf5
background=#3e4045

[wifi]
command=echo " $(~/.config/i3/scripts/rofi-wifi-menu) "
interval=5
# background=#3e4045
# color=#c0caf5

[keybindings]
full_text=   
command=~/.config/i3/scripts/keyhint-2
# color=#c0caf5

[ppd_menu]
command=echo " $(~/.config/i3/scripts/ppd-status | awk '{print substr($0, 1, 2)}') "
signal=12
# color=#c0caf5
interval=once

[shutdown_menu]
command=~/.config/i3/scripts/powermenu
full_text=   
# color=#c0caf5
