align=center
separator=false
color=#f8f8f2
separator_block_width=2
markup=pango

[window_title]
command=echo " <b>$(~/.config/i3/scripts/window-title)</b> "
interval=once
signal=1
markup=pango
color=#24283b
background=#c0caf5

[time]
command=echo " <b>$(date '+%Hh%M')</b> "
interval=1
color=#c0caf5

[mediaplayer]
command=echo " $( ~/.config/i3/scripts/mediaplayer ) "
interval=once
signal=10
background=#24283b
color=#c0caf5

[volume-mic]
command=echo " $(~/.config/i3/scripts/volume-mic) "
instance=Master
interval=once
signal=11
background=#24283b
color=#c0caf5

[arch_update]
command=echo "   $(checkupdates | wc -l) "
interval=once
background=#24283b
color=#c0caf5

[disk]
instance=/
command=echo "   $(df -h / | awk 'FNR==2 { gsub(/[A-Za-z]/, ""); printf "%i\n", $4 }') GiB "
interval=30
background=#24283b
color=#c0caf5

[gpu_stats]
command=echo " <b>GPU:</b> $(nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits | awk '{ printf "%02i% ", $0}' && nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits | awk '{ printf " %i°C\n", $0}') "
interval=2
color=#c0caf5
background=#24283b

[cpu_stats]
command=echo " <b>CPU:</b> $(sh -c 'usage=$(LC_ALL=C sar -u 1 1 | awk '\''/^Average:/ { printf "%.1f% ", 100 - $8 }'\''); temp=$(LC_ALL=C sensors | awk '\''/Package id 0:/ { gsub(/[+°C]/, "", $4); printf " %.0f°C", $4; exit } /Core 0:/ { gsub(/[+°C]/, "", $3); printf " %.0f<span color=\"#ff5555\">°C</span>", $3; exit }'\'' ); echo "$usage$temp"') "
interval=2
color=#c0caf5
background=#24283b

[memory]
command=echo "   $(free --giga | awk 'FNR==2{ printf "%i\n", $7 }') GiB "
interval=2
color=#c0caf5
background=#24283b

[battery]
command=echo " $(~/.config/i3/scripts/battery2)  "
interval=30
color=#c0caf5
background=#24283b

[keybindings]
full_text=   
command=~/.config/i3/scripts/keyhint
color=#c0caf5

[ppd_menu]
command=echo " $(if [ $button ]; then ~/.config/i3/scripts/power-profiles; else ~/.config/i3/scripts/ppd-status | awk '{print substr($0, 1, 2)}' ; fi) "
interval=5
onclick=~/.config/i3/scripts/power-profiles
color=#c0caf5

[shutdown_menu]
command=~/.config/i3/scripts/powermenu
full_text=   
color=#c0caf5
