#!/bin/bash

workspaces() {
	a=$(hyprctl monitors | awk 'FNR == 7 { print $3 }')
	o=$(hyprctl workspaces | awk '{ print $4 }' | egrep -o '[0-9]+')

	w1=bar-ws
	w2=bar-ws
	w3=bar-ws
	w4=bar-ws
	w5=bar-ws
	w6=bar-ws
	w7=bar-ws
	w8=bar-ws
	w9=bar-ws
	w10=bar-ws

	icon1=./images-dark/a0.svg
	icon2=./images-dark/a1.svg
	icon3=./images-dark/a2.svg
	icon4=./images-dark/a3.svg
	icon5=./images-dark/a4.svg
	icon6=./images-dark/a5.svg
	icon7=./images-dark/a6.svg
	icon8=./images-dark/a7.svg
	icon9=./images-dark/a8.svg
	icon10=./images-dark/a9.svg

	for i in $o; do
		eval "w$i=bar-occupied-ws"
	done

	if [[ $a -eq 1 ]]; then
		w1=bar-active-ws
	elif [[ $a -eq 2 ]]; then
		w2=bar-active-ws
	elif [[ $a -eq 3 ]]; then
		w3=bar-active-ws
	elif [[ $a -eq 4 ]]; then
		w4=bar-active-ws
	elif [[ $a -eq 5 ]]; then
		w5=bar-active-ws
	elif [[ $a -eq 6 ]]; then
		w6=bar-active-ws
	elif [[ $a -eq 7 ]]; then
		w7=bar-active-ws
	elif [[ $a -eq 8 ]]; then
		w8=bar-active-ws
	elif [[ $a -eq 9 ]]; then
		w9=bar-active-ws
	elif [[ $a -eq 10 ]]; then
		w10=bar-active-ws
	fi

	l1="(label :class \"$w1\" :text \"0\")"
	l2="(label :class \"$w2\" :text \"1\")"
	l3="(label :class \"$w3\" :text \"2\")"
	l4="(label :class \"$w4\" :text \"3\")"
	l5="(label :class \"$w5\" :text \"4\")"
	l6="(label :class \"$w6\" :text \"5\")"
	l7="(label :class \"$w7\" :text \"6\")"
	l8="(label :class \"$w8\" :text \"7\")"
	l9="(label :class \"$w9\" :text \"8\")"
	l10="(label :class \"$w10\" :text \"9\")"

	if [[ $w1 == 'bar-ws' ]]; then
		l1=""
	fi

	if [[ $w2 == 'bar-ws' ]]; then
		l2=""
	fi

	if [[ $w3 == 'bar-ws' ]]; then
		l3=""
	fi

	if [[ $w4 == 'bar-ws' ]]; then
		l4=""
	fi

	if [[ $w5 == 'bar-ws' ]]; then
		l5=""
	fi

	if [[ $w6 == 'bar-ws' ]]; then
		l6=""
	fi

	if [[ $w7 == 'bar-ws' ]]; then
		l7=""
	fi

	if [[ $w8 == 'bar-ws' ]]; then
		l8=""
	fi

	if [[ $w9 == 'bar-ws' ]]; then
		l9=""
	fi

	if [[ $w10 == 'bar-ws' ]]; then
		l10=""
	fi

	echo "(box :class \"bar-workspace\" :orientation \"v\" :valign \"start\" $l1 $l2 $l3 $l4 $l5 $l6 $l7 $l8 $l9 $l10 )"

	#  echo "(box :class \"bar-workspace\" :orientation \"v\" :valign \"start\" (label :class \"$w1\" :text \"一\") (label :class \"$w2\" :text \"二\") (label :class \"$w3\" :text \"三\") (label :class \"$w4\" :text \"四\") (label :class \"$w5\" :text \"五\") (label :class \"$w6\" :text \"六\") (label :class \"$w7\" :text \"七\") (label :class \"$w8\" :text \"八\") (label :class \"$w9\" :text \"九\") (label :class \"$w10\" :text \"十\"))"
}

workspaces
socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r _; do
	workspaces
done
