#!/bin/bash

lvlalt=$(pamixer --get-volume)
zero="0"
third="33"
twothirds="66"
full="100"
mute="muted"

icon() {
	lvl=$(pamixer --get-volume)
	if [ "$lvl" == "$zero" ]; then
		echo "./images-v2/volume-zero.svg"
	elif [ "$(pamixer --get-mute)" == "true" ]; then
		echo "./images-v2/volume-off.svg"
	elif [ "$lvl" -lt "$third" ]; then
		echo "./images-v2/volume-low.svg"
	elif [ "$lvl" -lt "${twothirds}" ]; then
		echo "./images-v2/volume-medium.svg"
	else
		echo "./images-v2/volume-max.svg"
	fi
}

if [[ $1 == icon ]]; then
	icon
elif [[ $1 == text ]]; then
	lvl=$(pamixer --get-volume-human | xargs)
	if [[ "$lvl" == "$mute" ]]; then
		echo "0%"
	else
		echo $lvl
	fi
elif [[ $1 == up ]]; then
	pamixer --allow-boost -i 2 &
	pamixer --get-volume-human | xargs -I {} notify-send -r 123 "Volume" "{}"
elif [[ $1 == down ]]; then
	pamixer -d 2 &
	pamixer --get-volume-human | xargs -I {} notify-send -r 123 "Volume" "{}"
elif [[ $1 == number ]]; then
	num=$(pamixer --get-volume-human | awk -F'%' '{ print $1 }' | xargs)
	echo $num
fi
