#!/bin/bash
# strenght=$(nmcli -t -f IN-USE,SIGNAL dev wifi | grep '*' | cut -d: -f2)
strength=$(nmcli dev wifi | grep \* | awk -F'/' '{print $2}' | awk '{print $2}')
ssid=$(nmcli -f IN-USE,SSID -p dev wifi | grep \* | sed 's/\*  *//')
# state=$(iwconfig wlan0 | grep ESSID | awk -F':' '{ print $2 }' | xargs)
wf=$(echo "$strength*100/70" | bc)

icon() {
	if [[ $wf -eq 0 ]]; then
		echo "󰤭"
	elif [[ $wf -le 40 ]]; then
		echo "󰤟"
	elif [[ $wf -le 60 ]]; then
		echo "󰤢"
	elif [[ $wf -le 80 ]]; then
		echo "󰤥"
	elif [[ $wf -gt 80 ]]; then
		echo "󰤨"
	else
		echo "󰤯"
	fi
}

svg() {
	if [[ $wf -eq 0 ]]; then
		echo "./images-v2/wifi-off.svg"
	elif [[ $wf -le 30 ]]; then
		#   echo "./images/wifi-none.svg"
		echo "./images-v2/wifi-low"
	elif [[ $wf -le 60 ]]; then
		#   echo "./images/wifi-low.svg"
		echo "./images-v2/wifi-medium.svg"
	elif [[ $wf -gt 60 ]]; then
		#   echo "./images/wifi-medium.svg"
		echo "./images-v2/wifi-max.svg"
		# elif [[ $wf -gt 75 ]]; then
		#   echo "./images/wifi-high.svg"
	else
		echo "./images-v2/wifi-zero.svg"
	fi
}

if [[ $1 == icon ]]; then
	icon
elif [[ $1 == number ]]; then
	echo $wf
elif [[ $1 == percentage ]]; then
	echo "$wf%"
elif [[ $1 == name ]]; then
	echo "${ssid:-'Disconected'}"
fi
