preload = ~/.config/hypr/man-colors.jpg

#set the default wallpaper(s) seen on inital workspace(s) --depending on the number of monitors used
wallpaper = eDP-1,~/.config/hypr/man-colors.jpg
wallpaper = HDMI-A-1,~/.config/hypr/man-colors.jpg

ipc= off
