#!/usr/bin/env bash

usage=$(LC_ALL=C sar -u 1 1 | awk '/^Average:/ { printf "%02i", 100 - $8 }')

temp=$(sensors | awk '/Package id 0:/ { gsub(/[+°C]/, "", $4); printf "%.0f", $4; exit } /Core 0:/ { gsub(/[+°C]/, "", $3); printf "%.0f", $3; exit }')

if [ -n "$BLOCK_BUTTON" ]; then
	case "$BLOCK_BUTTON" in
		1) ghostty -e "btop --preset 1" >/dev/null 2>&1;;	# Opens btop
		2) ghostty -e "btop --preset 1" >/dev/null 2>&1;;	# Opens btop
		3) ghostty -e "btop --preset 1" >/dev/null 2>&1;;	# Opens btop
	esac
fi

echo "<b>CPU </b>$usage<small>% </small>$temp<small>°C</small>"
