#!/bin/bash
# ~/.config/i3/scripts/ppd_listener.sh
PPD_SIGNAL=6
gdbus monitor --system --dest net.hadess.PowerProfiles --object-path /net/hadess/PowerProfiles | while IFS= read -r line; do
  if [[ "$line" == *"ActiveProfile"* ]]; then
     pkill -RTMIN+${PPD_SIGNAL} i3blocks
  fi
done
