[defaults]
format = "{time}\n"
paused_state_text = "  "
resumed_state_text = "  "

[[sessions]]
id = "work"
name = "Work"
duration = "52m"
time_format = "%M"
command = "uairctl next && uairctl resume && notify-send 'Work Done!' && ffplay -t 11 -nodisp -autoexit ~/.config/uair/The_Wake_Up_-_Earth_Day.mp3"

[[sessions]]
id = "rest"
name = "Rest"
duration = "17m"
time_format = "%M"
command = "uairctl prev && uairctl resume && notify-send 'Rest Done!' && ffplay -t 11 -nodisp -autoexit ~/.config/uair/The_Wake_Up_-_Earth_Day.mp3"
